name: mindmap_graph
description: A cross-platform mind mapping and note-taking application with graph database support.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # 图数据库
  # 暂时注释掉 Neo4j，后续需要找到合适的图数据库实现
  # neo4j_dart: ^1.0.0
  
  # 图形界面
  # 由于 antv_x6 没有 Flutter 版本，我们可以使用其他图形库
  graphview: ^1.2.0  # 用于绘制图形
  
  # 状态管理
  provider: ^6.0.0
  
  # 存储
  path_provider: ^2.0.0
  shared_preferences: ^2.0.0
  
  # 同步
  dio: ^5.0.0  # 用于网络请求
  webdav_client: ^1.2.0
  
  # 工具
  json_annotation: ^4.8.1
  logging: ^1.2.0
  
  # WebView
  webview_flutter: ^4.4.2  # 移动端支持
  webview_flutter_web: ^0.2.2+3  # Web平台支持
  webview_windows: ^0.3.0  # Windows平台支持
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/web/graph.html